#####
# Configuration file for iris-export-builder
# Syntax is TOML (https://toml.io/en/).

##### Details about the source files
[Source]

# The type of location: 'directory' or 'github'
type = 'github'

# The encoding of the source files, e.g. UTF-8 (default) or CP1252.
encoding = 'UTF-8'

# The type of source code export: 'xml' or 'udl' (default).
srctype = 'udl'

# Directory, relative to the sources root, of the source files.
srcdir = 'src'

# Directory to search for CSP files, if any.
cspdir = 'csp'

# Directory to search for data files to include, if any.
datadir = 'data'

# List of items to skip when building the export. Supports *-style wildcards.
# The items are matched against their full path from the root of the repository.
skip = [
]


# Details on what to do with CSP items
[CSP]

# How to handle the CSP export: 'embed', 'separate' or 'none'.
export = 'embed'


# One or more parsers for CSP items.
[[CSP.parsers]]

# The regular expression to use to match application and item.
regex = '((/csp)?/[^/]+)/(.+)'
# The application part; can use a capture group, e.g. '\1', or be hardcoded.
app = '\1'
# The item part can also use capture groups
item = '\3'
# If an item does not match: 'error' or 'skip'
nomatch = 'error'


##### Data items
[Data]

# How to handle the data export: 'embed', 'separate', or 'none'
export = 'embed'


##### GitHub details
[GitHub]

# GitHub username (repo owner) and repository
user = ''
repo = ''

# Tag/branch/commit id  to create an export for.
tag = 'master'

# GitHub security token to use, if needed.
# Prefix with @ to specify a file containing the token.
token = ''


##### Details about the directory containing the source files
[Directory]

# The path to the repository/checkout
path = ''


##### Server connection details: the server to use to convert UDL to XML.
[Server]

# Hostname or IP address, default 'localhost'
#host = ''
# Caché/IRIS internal web server port, default '52773'
#port = ''
# Namespace to use (default 'USER')
#namespace = ''
# Credentials; default 'SuperUser'/'SYS'
#user = ''
#password = ''
# Whether to connect with HTTPS (default false)
#https = false


##### Details about the export to build and logging
[Local]

# File to place output in. Supports escapes:
# {name}: top-level directory in filesystem or GitHub zip
# {cfgname}: name (without extension) of configuration file
# {timestamp}: Current date/time in format YYYY-MM-DDThh-mm
outfile = '{name}.xml'

# Whether to create an Ensemble deployment file.
deployment = false

# Directory for the log file.
logdir = ''

# Logging level. One of 'debug', 'info', 'warning', 'error', or 'critical'.
loglevel = 'info'

# Timestamp handling. One of 'clear', 'update', or 'leave' (default).
timestamps = 'leave'

# Force override of export version. Either 25 (Cache) or 26 (IRIS).
export_version = ''

# Augment/override settings in this file with the one specified here.
augment_from = ''
